# Starter pipeline
pool:
 vmImage: ubuntu-latest
  
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '`6d63db4c-a5ee-43e6-8cc5-36ef2e7b52d3`' #Authorize and in the task editor
    ScriptType: 'pscore'
    scriptLocation: 'inlineScript'
    Inline: 'az vmss extension set --resource-group dailylearn-prod-app-rg --vmss-name test-vmss-n2 --name CustomScript  --force-update    --publisher Microsoft.Azure.Extensions    --version "2.0"    --settings '{"fileUris": ["https://dailylearnprodsa.blob.core.windows.net/dlscripts/dl-prod-deploy.sh?sp=r&st=2021-11-15T10:13:00Z&se=2021-11-16T18:13:00Z&spr=https&sv=2020-08-04&sr=b&sig=v13SoQ9MMN0JPk5dYwAjFRwF8e2dH9gNs%2FgtmrqbWxc%3D"],"commandToExecute": "sh dl-prod-deploy.sh"}''